name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Set up JDK 21
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      # 3. Cache Gradle dependencies
      - name: Cache Gradle packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper/
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-${{ runner.os }}-

      # 4. Make Gradle wrapper executable
      - name: Make Gradle wrapper executable
        run: chmod +x ./gradlew

      # 5. Build the project (compile + tests)
      - name: Build project
        run: ./gradlew clean build --refresh-dependencies --no-daemon

      # 6. Publish test results to GitHub UI
      - name: Publish unit test results
        uses: dorny/test-reporter@v2
        if: ${{ !cancelled() }}
        with:
          name: Unit Tests
          path: build/test-results/test/*.xml
          reporter: junit-xml

